### PR TITLE
Provide the ability for the CoreDataStackFactory user to supply their…

### PR DESCRIPTION
**Pull request by troya2**
## Pull request checklist

- [ √ ] All tests pass. Demo project builds and runs.
- [ √ ] I have resolved any merge conflicts.
- [ √ ] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

## What's in this pull request?

For a current project, I needed to supply a custom NSPersistentStoreCoordinator subclass so I could support an encrypted backing store.  This pull request adds the ability to supply an optional factory method to the CoreDataStackFactory that allows the user of the factory to do just that.  I included test coverage and all tests pass.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @troya2 ! 😄 

I'm *really* not sure about subclassing `NSPersistentStoreCoordinator`. That seems incredibly risky, and I'm not sure that's recommended. Some classes in the Cocoa frameworks are *not* meant to be subclassed. I just checked the docs for `NSPersistentStoreCoordinator` and didn't see any notes on subclassing, so I'm not 100% in this case if subclassing is supported or not.

>  ...so I could support an encrypted backing store.

Have you looked at the [`NSPersistentStore `](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSPersistentStore_Class/) API? (NSHipster [article here](http://nshipster.com/nsincrementalstore/).) This allows you to provide custom stores for CoreData.

My guess is that *this* is what you want, not a subclass of `NSPersistentStoreCoordinator`...

**Comment by jessesquires** [comment]
Hey @troya2 😄 

Just spoke with some other developers about this, and the consensus was that subclassing the PSC is *not a very good idea*. I'd highly recommend investigating other strategies with CoreData (like a custom store), or potentially other database solutions altogether. 😅

**Comment by troya2** [comment]
The problem is that I'm integrating with Good (Blackberry) who supplies a subclass of NSPersistentStoreCoordinator to implement their encrypted incremental store.  I have to use that to be in the good marketplace, however risky that may be.  Without this ability, I cannot use your awesome code.  Any suggestions?

**Comment by jessesquires** [comment]
Ugh. 😕 I see... 

> I have to use that to be in the good marketplace, however risky that may be.

If you have contacts for the authors of that library, but I would probably report this with them.

> Without this ability, I cannot use your awesome code. 

Aw thanks 😊 Here's what I would do:

- Keep your custom fork and point CocoaPods/Carthage to your custom fork in your Podfile/Cartfile. This way, you can still use the library but with this patch applied.
- When I release new versions of `JSQCoreDataKit`, you can simply merge into your fork.

**Comment by troya2** [comment]
Can you provide more on your thinking of it being risky to subclass NSPersistentStoreCoordinator.  In other Apple docs where subclassing is discouraged, their documentation says so.  I didn't come across that in this case.  Good is a big player in the enterprise mobile device management space.  If really is a risky practice, and I can point them to some information on that, I will certainly report it to them and see if they can provide an incremental store that can work with a vanilla NSPersistentStoreCoordinator.

**Comment by jessesquires** [comment]
Hey @troya2 😄 

A few things:

- Subclassing PSC to modify behavior based on a store feels very wrong. It's responsibility is coordinating between stores and models. If you need to subclass it to provide a custom store type, that seems like you're leaking implementation details of the store into the coordinator.
- The docs may not explicitly discourage subclassing, but the class does not seemed to be designed with subclassing in mind. Typically, classes designed for subclassing will have a "Subclassing Notes" section (like `UIView`, for example).
- I asked [Daniel Eggert](https://www.objc.io/books/core-data/) about this, and his response was that there isn't any good reason to subclass the PSC. 😄

**Comment by jessesquires** [comment]
Also, btw — do you have a link to this library? Never heard of "Good" 😕

**Comment by troya2** [comment]
Thank you.  I'll see if I can move the battleship.  Meanwhile, I'll maintain my branch and stay in sync.  I appreciate your response and feedback.  Hope to see you next week!

**Comment by troya2** [comment]
Here's a link to Good's website.  https://community.good.com/community/gdn
Unfortunately, most of the links on that page require you to log in as a technology partner.  I'm in the WWDC labs ATM sitting next to Daniel Eggert to see what he thinks of their implementation and to see if he can provide additional motivation for them to avoid subclassing NSPersistentStoreCoordinator.

**Pull request closed without merging**
