### PR TITLE
Use iOS 9 method for properly destroying persistent store. 

### LINKED ISSUE #104: Destroying persistent store with iOS 9 NSPersistentStoreCoordinator method.
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/README.md) and [docs](http://www.jessesquires.com/JSQCoreDataKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQCoreDataKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 6.0.1

As of iOS 9 Apple provides `destroyPersistentStore(at:ofType:options:)` method for `NSPersistentStoreCoordinator`.  Would you consider conditionally replacing following methods(https://github.com/jessesquires/JSQCoreDataKit/blob/develop/Source/CoreDataStack.swift#L166-L167) with the new one? 

Something like

```swift
if #available(iOS 9, tvOS 9, *) {
    try model.removeExistingStore()
    try storeCoordinator.remove(store)
} else {
    try storeCoordinator.destroyPersistentStore(...)
}
```

### PR DESCRIPTION
**Pull request by DenHeadless**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

#### This fixes issue #

Closes #104.

## What's in this pull request?

Use iOS 9 `destroyPersistentStore(at:ofType:options:)` method to properly cleanup persistent store.

### CODE REVIEW

**Comment by DenHeadless** [comment]
CI failures look completely unrelated to changes in this PR. Tests pass locally on my machine on both macOS and iOS.

**Comment by jessesquires** [comment]
Thanks @DenHeadless ! 💯

**Comment by jessesquires** [comment]
I updated the branch. Let's see what travis says now. 😄

**Comment by jessesquires** [comment]
Thanks again @DenHeadless ! 💯

**Pull request merged**
