### PR TITLE
Move `resetStack` to `CoreDataStackFactory`

### PR DESCRIPTION
**Pull request by Liquidsoul**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

## What's in this pull request?
- `resetStack` is now a static method of `CoreDataStackFactory`

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @Liquidsoul ! 🎉 

Annnd, I'm dumb. Looking at this, I was thinking "this feels weird." Then, I realized that this makes more since as an instance method on `CoreDataStack`. What do you think? 

We can update the method signature to: `reset(onQueue queue: completion: )`

Sorry for the churn! 😄

**Comment by Liquidsoul** [comment]
My bad, I should have listen to my fingers when I tried to remove the `stack:` argument and it did not work.
I should have stopped right there and think 😅 
I'll change this.

**Comment by jessesquires** [comment]
Also, a quick note: this means the stack will pass *itself* to the completion block. Might be a bit odd, but I think this is good. Then you won't have to capture the stack in the closure via `self.stack` if you need to do extra work after the reset.

**Comment by Liquidsoul** [comment]
Just updated and rebased the branch. Do you want me to squash the commits together?

**Comment by jessesquires** [comment]
Looks awesome! 🎉 I'll squash via github. 👍

**Pull request merged**
