### PR TITLE
Added Framework Search Paths to ExampleModel project (#100)

### PR DESCRIPTION
**Pull request by darkhonor**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

## What's in this pull request?
Added Search Framework Path to the ExampleModel project to locate the JSQCoreDataKit.framework built during carthage build

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @darkhonor !

**Comment by tonyarnold** [comment]
Hi @darkhonor — thanks for the attempt to fix this, however you probably need:

```
FRAMEWORK_SEARCH_PATHS = $(inherited) $(CONFIGURATION_BUILD_DIR)
```

**Comment by tonyarnold** [comment]
I don't think this is the correct solution to the problem at hand. Unless Carthage needs to run tests, it shouldn't be building the example models. You probably want to make the schemes for the example models not shared. Carthage doesn't build any targets that don't have shared schemes.

**Comment by jessesquires** [comment]
Thanks @tonyarnold! -- Yeah, that was my initial reaction. Then I realized that schemes need to be shared for travis. So I was like `¯\_(ツ)_/¯ `

Maybe we don't need this:
https://github.com/jessesquires/JSQCoreDataKit/blob/develop/.travis.yml#L47

since that `ExampleModel` project should get built implicitly via the `Example` project...

**Comment by tonyarnold** [comment]
I'll pull it out of my branch, `xcodebuild` should handle it for us.

**Comment by darkhonor** [comment]
@jessesquires , made the suggested changes.  Let me know what you think

**Comment by jessesquires** [comment]
Thanks @darkhonor !

The first commit is still in here, but it looks like #102 takes care of that + updating travis.

Going to close this in favor of #102, but we'll still give you credit in the release notes! 😄

**Pull request closed without merging**
