### PR TITLE
Update Xcode10.1, Swift4.2, prep 8.0 release

### LINKED ISSUE #119: Make PersistentStoreOptions [AnyHashable: Any]
Missed this update.

Unfortunately this is a breaking change.

### LINKED ISSUE #125: Upgrade to Swift 4.2

### PR DESCRIPTION
**Pull request by jessesquires**
- Update to Xcode 10.1
- Update to Swift 4.2 (close #125)
- iOS 11.0 minimum
- tvOS 11.0 minimum
- macOS 10.12 minimum
- watchOS 4.0 minimum
- Fix #119
- Bump library to v8.0
- Update README
- Update SwiftLint to 0.27.0

### CODE REVIEW

**Comment by jessesquires** [comment]
@tonyarnold @Liquidsoul anyone want to help debugging travis? i'm not sure how to fix this:

```
error: Multiple commands produce '/Users/travis/Library/Developer/Xcode/DerivedData/JSQCoreDataKit-ehglwcnbceiuhzblfbczcnrkdltw/Build/Products/Debug-iphonesimulator/JSQCoreDataKit.framework':
```

🤷‍♂️ 😭

**Comment by gaelfoppolo** [comment]
I also run the command locally and was able to reproduce.
I updated the `PRODUCT_NAME` in the `JSQCoreDataKit-iOS` target and the issue stopped.

**Comment by jessesquires** [comment]
thanks @gaelfoppolo !

Yeah, I was working on this again this morning. The issue is with the cross-platform framework.

Editing `PRODUCT_NAME` was causing some other issues for me with imports, which need to change to `import JSQCoreDataKit_iOS`, `import JSQCoreDataKit_macOS`, etc. I think this was because `PRODUCT_MODULE_NAME` was also updated.

I *think* what we want is distinct product names for each platform, but the same module name.

I might try this approach instead:

https://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/
http://ilya.puchka.me/xcode-cross-platform-frameworks/

**Comment by gaelfoppolo** [comment]
This look promising if you seek consistency in imports statements. And on top of it, this is simpler!

**Comment by jessesquires** [comment]
🎉 First test failed just because of `pod lib lint` (expected). going to merge.

**Pull request merged**
