### PR TITLE
Rename context property

### PR DESCRIPTION
**Pull request by tonyarnold**
Addresses #9 in lieu of #16.

### CODE REVIEW

**Comment by jessesquires** [comment]
thanks @tonyarnold ! :smile:

**Comment by jessesquires** [comment]
hey @tonyarnold -- i'm going through PRs and adding people as collaborators on github. would you be interested in being added?

**Comment by tonyarnold** [comment]
@jessesquires I'll pitch in as I can. I don't have a lot of free time, but I'm happy to help.

**Comment by jessesquires** [comment]
Thanks @tonyarnold ! 😄 No pressure at all. 

I'm just trying to be more open and add collaborators more often. 😊

**Pull request merged**
