### PR TITLE
[Chore] Removed danger-auto_label gem 

### PR DESCRIPTION
**Pull request by kevnm67**
- [x] *Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*

Issue #

## Describe your changes

Removed danger-auto_label gem, which isn't being used by danger.

### CODE REVIEW

**Comment by kevnm67** [comment]
Danger, don't point out a missing milestone!  😎 (it ain't possible).

**Comment by jessesquires** [comment]
thanks @kevnm67 ! 🙌🏼 

unfortunately, there's a limitation with GH actions, so things like Danger do not work on PR forks.

**Comment by jessesquires** [comment]
I thought you were already added to this repo because of previous contributions, but you weren't. Just sent an invite. 😊

**Comment by kevnm67** [comment]
> I thought you were already added to this repo because of previous contributions, but you weren't. Just sent an invite. 😊

🤷 All good!  

Yeah, I created a PR against my forks dev branch + my personal bot token to ensure nothing broke.  It's unfortunate forked PR's fail because of this...

**Pull request merged**
