### PR TITLE
Don’t share the Example Model schemes

### PR DESCRIPTION
**Pull request by tonyarnold**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

#### This fixes issue #

This fixes issue #100

## What's in this pull request?

I've marked the ExampleModel-* schemes as not shared so that Carthage does not try to build them. They're still available to the tests in Xcode.

### CODE REVIEW

**Comment by jessesquires** [comment]
mind adding:

```
cache:
   - cocoapods
```

to travis?

**Comment by tonyarnold** [comment]
Not at all, 8aa67043a0d6aaf5af448c0a436bb7eacd036505.

Let's see if Travis actually builds. It's tripping over quite a bit today.

**Comment by tonyarnold** [comment]
Has @codecov-io just given up the ghost? 😦

**Comment by stevepeak** [comment]
@jessesquires I'm seeing :  `branch fix/example-models ignored` in the logs: https://codecov.io/gh/jessesquires/JSQCoreDataKit/commit/051f843f6283a2dc341b927beb5b71ca5dc06839/builds

**Pull request merged**
